name: 'crawler and frontend'

on:
  push:
    paths-ignore:
      - 'json/version-position.json'
    branches:
      - main
jobs:
  crawler:
    name: 'crawler: to get dataSource'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: install
        run: npm install
      - name: 'to test auto commit && copy data'
        run: 'node ./src/__tests__/testAutoCommit.js'
      # - name: 'to get all position by version'
      # run: 'node ./src/getPositionByVersion.js -m all'
      # - name: 'to get position-os list'
      #   run: 'node ./src/getPositionWithOsList.js'
      # - name: 'to generate final json (ver-pos-os, ver-pos-link'
      #   run 'node ./src/verPosOsGen'
      - name: commit version-position.json file to this repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: json/version-position.json
          commit_message: 'feat: update JSON file'
          commit_user_name: MrSeaWave
          commit_user_email: MrDaemon@outlook.com
      - name: 'Push JSON To dataSource repository'
        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.COPY_TO_THIS_FOLDER_TOKEN_GITHUB }}
        with:
          source_folder: 'json'
          destination_repo: 'MrSeaWave/chromium-history-dataSource'
          destination_folder: 'json'
          destination_branch: 'main'
          user_email: 'MrDaemon@outlook.com'
          user_name: 'MrSeaWave'
          commit_msg: 'feat: update JSON data'
