name: 'crawler and frontend 🚀'

on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'
  push:
    paths-ignore:
      - 'json/version-position.json'
    branches:
      - main
jobs:
  crawler:
    name: 'crawler: to get dataSource'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: global Yarn
        run: npm install -g yarn
      - name: Print Env
        run: |
          echo "node"
          node -v
          echo "npm"
          npm -v
          echo "yarn"
          yarn -v
          
      - name: install
        run: yarn install
      # - name: 'to test auto commit && copy data'
      #   run: 'node ./src/__tests__/testAutoCommit.js'
      - name: 'to get all position by version'
        run: 'node ./src/getPositionByVersion.js -m inc'
      - name: 'to get position-os list'
        run: 'node ./src/getPositionWithOsList.js'
      - name: 'to generate final json (ver-pos-os, ver-pos-link'
        run: 'node ./src/verPosOsGen'
      - name: commit version-position.json file to this repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: json/version-position.json
          commit_message: 'feat: update JSON file'
          commit_user_name: MrSeaWave
          commit_user_email: MrDaemon@outlook.com
      - name: 'Push JSON To dataSource repository'
        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.COPY_TO_OTHER_FOLDER_TOKEN_GITHUB }}
        with:
          source_folder: 'json'
          destination_repo: 'MrSeaWave/chromium-history-dataSource'
          destination_folder: 'json'
          destination_branch: 'main'
          user_email: 'MrDaemon@outlook.com'
          user_name: 'MrSeaWave'
          commit_msg: 'feat: update JSON data'
      - name: 'Push JSON to frontend repository'
        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.COPY_TO_OTHER_FOLDER_TOKEN_GITHUB }}
        with:
          source_folder: 'json/ver-pos-os'
          destination_repo: 'MrSeaWave/chromium-history-page'
          destination_folder: 'public/json/ver-pos-os'
          destination_branch: 'main'
          user_email: 'MrDaemon@outlook.com'
          user_name: 'MrSeaWave'
          commit_msg: 'feat: update JSON data'
  frontend:
    name: Deploy 🚀
    needs: crawler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          repository: MrSeaWave/chromium-history-page
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: In MrSeaWave/chromium-history-page To Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.DEPLOY_ANOTHER_TOKEN }}
          repository-name: MrSeaWave/chromium-history-page
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
